file(GLOB GFS_UNIT_TEST_SRCS CONFIGURE_DEPENDS unit/*.cc)
if(GFS_UNIT_TEST_SRCS)
  add_executable(gfs_unit_tests ${GFS_UNIT_TEST_SRCS})
  target_link_libraries(gfs_unit_tests PRIVATE gfs_master_lib gfs_chunkserver_lib gfs_client GTest::gtest GTest::gtest_main)
  add_test(NAME unit COMMAND gfs_unit_tests)
endif()

file(GLOB GFS_CLUSTER_TEST_SRCS CONFIGURE_DEPENDS integration/*.cc)
if(GFS_CLUSTER_TEST_SRCS)
  add_executable(gfs_cluster_tests ${GFS_CLUSTER_TEST_SRCS})
  target_link_libraries(gfs_cluster_tests PRIVATE gfs_client GTest::gtest GTest::gtest_main)
  target_compile_definitions(gfs_cluster_tests PRIVATE GFS_BIN_DIR="${CMAKE_BINARY_DIR}/bin")
  add_dependencies(gfs_cluster_tests gfs_master gfs_chunkserver)
  add_test(NAME cluster COMMAND gfs_cluster_tests)
endif()
