file(GLOB GFS_MASTER_SRCS CONFIGURE_DEPENDS *.cc)
list(FILTER GFS_MASTER_SRCS EXCLUDE REGEX "main\\.cc$")
if(GFS_MASTER_SRCS)
  add_library(gfs_master_lib STATIC ${GFS_MASTER_SRCS})
  target_link_libraries(gfs_master_lib PUBLIC gfs_common)
else()
  add_library(gfs_master_lib INTERFACE)
  target_link_libraries(gfs_master_lib INTERFACE gfs_common)
endif()
add_executable(gfs_master main.cc)
target_link_libraries(gfs_master PRIVATE gfs_master_lib)
