file(GLOB GFS_CHUNKSERVER_SRCS CONFIGURE_DEPENDS *.cc)
list(FILTER GFS_CHUNKSERVER_SRCS EXCLUDE REGEX "main\\.cc$")
if(GFS_CHUNKSERVER_SRCS)
  add_library(gfs_chunkserver_lib STATIC ${GFS_CHUNKSERVER_SRCS})
  target_link_libraries(gfs_chunkserver_lib PUBLIC gfs_common)
else()
  add_library(gfs_chunkserver_lib INTERFACE)
  target_link_libraries(gfs_chunkserver_lib INTERFACE gfs_common)
endif()
add_executable(gfs_chunkserver main.cc)
target_link_libraries(gfs_chunkserver PRIVATE gfs_chunkserver_lib)
